name: Build and deploy ouija app to Vercel
on:
  push:
    branches: ["master"]
    paths: 
      - 'apps/ouija/**'
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - name: Build Next.js App
        run: yarn build:ouija
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Next.js App
        run: |
          # Add any additional deployment steps or commands
          # Deploy to Vercel using the Vercel CLI or GitHub Actions Vercel action
          vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm